version: '3.7'

services:
  mysql1:
    image: mariadb
    container_name: mysql1
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=test1
      - MYSQL_USER=test1
    networks:
      testnet1:
        ipv4_address: 172.30.1.50
  php1:
    build: config/docker/php
    container_name: php1
    restart: always
    links:
      - mysql1
    working_dir: /var/www
    user: $PHP_UID:$PHP_GID # $(id -u):$(id -g)
    volumes:
      - .:/var/www
    depends_on:
      - mysql1
    networks:
      testnet1:
        ipv4_address: 172.30.1.51
  nginx1:
    image: nginx:alpine
    container_name: nginx1
    restart: always
    working_dir: /etc/nginx/conf.d/
    volumes:
      - .:/var/www:rw
      - ./config/docker/nginx:/etc/nginx/conf.d:ro
    ports:
      - "6123:80"
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - php1
    networks:
      testnet1:
        ipv4_address: 172.30.1.52

volumes:
  db1:

networks:
  testnet1:
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24